# Generated by Django 3.0.2 on 2020-01-07 15:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='tbl_sector',
            fields=[
                ('idSector', models.AutoField(primary_key=True, serialize=False, unique=True)),
                ('nombre', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='tbl_usuarios',
            fields=[
                ('idUsuario', models.AutoField(primary_key=True, serialize=False, unique=True)),
                ('username', models.CharField(max_length=50, unique=True)),
                ('correo', models.EmailField(max_length=250)),
                ('contrasena', models.CharField(max_length=20)),
                ('idSector', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='ecoteamBD.tbl_sector')),
            ],
        ),
        migrations.CreateModel(
            name='tbl_puntoRecoleccion',
            fields=[
                ('idPunto', models.AutoField(primary_key=True, serialize=False, unique=True)),
                ('nombre', models.CharField(max_length=50)),
                ('descripcion', models.CharField(max_length=250)),
                ('latitud', models.DecimalField(decimal_places=20, max_digits=20)),
                ('longitud', models.DecimalField(decimal_places=20, max_digits=20)),
                ('idSector', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='ecoteamBD.tbl_sector')),
            ],
        ),
        migrations.CreateModel(
            name='tbl_horarioRecoleccion',
            fields=[
                ('idHorario', models.AutoField(primary_key=True, serialize=False, unique=True)),
                ('horaInicio', models.DateTimeField()),
                ('horaFin', models.DateTimeField()),
                ('idPunto', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='ecoteamBD.tbl_puntoRecoleccion')),
            ],
        ),
        migrations.CreateModel(
            name='tbl_denuncias',
            fields=[
                ('idDenuncia', models.AutoField(primary_key=True, serialize=False, unique=True)),
                ('motivo', models.CharField(max_length=30)),
                ('direccion', models.CharField(max_length=200)),
                ('descripcion', models.CharField(max_length=250)),
                ('foto', models.ImageField(upload_to='')),
                ('idUsuario', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='ecoteamBD.tbl_usuarios')),
            ],
        ),
    ]
