# Generated by Django 3.0.2 on 2020-01-11 20:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecoteamBD', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='tbl_denuncias',
            name='activado',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='tbl_horariorecoleccion',
            name='activado',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='tbl_puntorecoleccion',
            name='activado',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='tbl_sector',
            name='activado',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='tbl_usuarios',
            name='activado',
            field=models.BooleanField(default=True),
        ),
    ]
