name: apppractice
description: A new Flutter project.

version: 1.0.0+1

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  curved_navigation_bar: 
  flutter:
    sdk: flutter

 
  cupertino_icons: ^0.1.2
  image_picker: ^0.5.3+1
  font_awesome_flutter: ^8.2.0
  firebase_database: ^3.1.1
  flutter_map: ^0.8.2
  latlong: ^0.6.1
  http: ^0.12.0+4
  firebase_auth: ^0.15.3+1
  firebase_core: ^0.4.3+2
  cloud_firestore: ^0.13.0+1
  provider: ^4.0.2
  firebase_storage: ^3.1.1
  geocoder: ^0.2.1

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:

  uses-material-design: true
  assets: 
        - assets/images/
        
  fonts:
  - family:          Chewy
    fonts:
     - asset:        assets/fonts/Chewy.ttf

module:
    androidX: true